import type { LabTest, LabPackage, Booking, TestResult, Collector, TimeSlot } from './types';

export const labTests: LabTest[] = [
  {
    id: '1',
    name: 'Complete Blood Count',
    description: 'Checks your red blood cells, white blood cells, and platelets to see how healthy your blood is',
    price: 800,
    category: 'Hematology',
    turnaroundTime: '24 hours',
    requirements: ['Fasting not required'],
    popular: true,
  },
  {
    id: '2',
    name: 'Cholesterol Check',
    description: 'Tests your cholesterol levels to check your heart health and risk of heart disease',
    price: 1500,
    category: 'Cardiovascular',
    turnaroundTime: '24 hours',
    requirements: ['12-hour fasting required'],
    popular: true,
  },
  {
    id: '3',
    name: 'Blood Sugar Test',
    description: 'Checks your blood sugar levels to screen for diabetes',
    price: 400,
    category: 'Diabetes',
    turnaroundTime: '12 hours',
    requirements: ['8-12 hour fasting required'],
    popular: true,
  },
  {
    id: '4',
    name: 'Liver Health Check',
    description: 'Tests how well your liver is working and checks for any liver problems',
    price: 2000,
    category: 'Liver',
    turnaroundTime: '24 hours',
    requirements: ['Fasting not required'],
  },
  {
    id: '5',
    name: 'Kidney Health Check',
    description: 'Checks how well your kidneys are working and filters waste from your blood',
    price: 1800,
    category: 'Kidney',
    turnaroundTime: '24 hours',
    requirements: ['Fasting not required'],
  },
  {
    id: '6',
    name: 'Thyroid Function Test',
    description: 'Checks your thyroid hormone levels to see if your thyroid is working properly',
    price: 2500,
    category: 'Thyroid',
    turnaroundTime: '48 hours',
    requirements: ['Fasting not required', 'Morning sample preferred'],
    popular: true,
  },
  {
    id: '7',
    name: '3-Month Blood Sugar Average',
    description: 'Shows your average blood sugar levels over the past 3 months',
    price: 1200,
    category: 'Diabetes',
    turnaroundTime: '24 hours',
    requirements: ['Fasting not required'],
  },
  {
    id: '8',
    name: 'Urine Test',
    description: 'Checks your urine for signs of infection, kidney problems, or other health issues',
    price: 500,
    category: 'General',
    turnaroundTime: '12 hours',
    requirements: ['Mid-stream sample required'],
  },
  {
    id: '9',
    name: 'Malaria Test',
    description: 'Quick test to check if you have malaria',
    price: 600,
    category: 'Infectious Disease',
    turnaroundTime: '2 hours',
    requirements: ['Fasting not required'],
  },
  {
    id: '10',
    name: 'HIV Test',
    description: 'Confidential test to check for HIV infection',
    price: 800,
    category: 'Infectious Disease',
    turnaroundTime: '30 minutes',
    requirements: ['Confidential counseling included'],
  },
  {
    id: '11',
    name: 'Vitamin D Check',
    description: 'Checks if you have enough vitamin D in your body',
    price: 2200,
    category: 'Vitamins',
    turnaroundTime: '48 hours',
    requirements: ['Fasting not required'],
  },
  {
    id: '12',
    name: 'Iron Level Check',
    description: 'Checks your iron levels to see if you have enough iron or if you might be anemic',
    price: 1800,
    category: 'Hematology',
    turnaroundTime: '24 hours',
    requirements: ['Morning sample preferred'],
  },
  {
    id: '13',
    name: 'DNA & Genetic Testing',
    description: 'Learn about your ancestry, health risks you might inherit, and genetic traits',
    price: 15000,
    category: 'Genetic',
    turnaroundTime: '7-14 days',
    requirements: ['Fasting not required', 'Saliva or blood sample'],
    popular: true,
  },
];

export const labPackages: LabPackage[] = [
  {
    id: 'pkg-1',
    name: 'Basic Health Check',
    description: 'Essential tests for routine health monitoring',
    tests: ['Complete Blood Count', 'Blood Sugar', 'Urine Test'],
    price: 1500,
    originalPrice: 1700,
    popular: true,
  },
  {
    id: 'pkg-2',
    name: 'Diabetes Care Package',
    description: 'Comprehensive diabetes monitoring panel',
    tests: ['Blood Sugar Test', '3-Month Blood Sugar Average', 'Kidney Health Check', 'Cholesterol Check'],
    price: 4500,
    originalPrice: 5900,
    popular: true,
  },
  {
    id: 'pkg-3',
    name: 'Executive Health Screening',
    description: 'Full body health assessment',
    tests: ['Complete Blood Count', 'Cholesterol Check', 'Liver Health Check', 'Kidney Health Check', 'Thyroid Function Test', 'Vitamin D Check'],
    price: 8500,
    originalPrice: 10800,
  },
  {
    id: 'pkg-4',
    name: 'Women\'s Wellness Package',
    description: 'Tailored health check for women',
    tests: ['Complete Blood Count', 'Thyroid Function Test', 'Iron Level Check', 'Vitamin D Check'],
    price: 6000,
    originalPrice: 7300,
  },
  {
    id: 'pkg-5',
    name: 'Cardiac Risk Assessment',
    description: 'Heart health evaluation',
    tests: ['Cholesterol Check', 'Blood Sugar Test', 'Complete Blood Count'],
    price: 2500,
    originalPrice: 2700,
  },
];

export const timeSlots: TimeSlot[] = [
  { id: '1', time: '07:00 AM', available: true },
  { id: '2', time: '08:00 AM', available: true },
  { id: '3', time: '09:00 AM', available: true },
  { id: '4', time: '10:00 AM', available: false },
  { id: '5', time: '11:00 AM', available: true },
  { id: '6', time: '12:00 PM', available: true },
  { id: '7', time: '02:00 PM', available: true },
  { id: '8', time: '03:00 PM', available: false },
  { id: '9', time: '04:00 PM', available: true },
  { id: '10', time: '05:00 PM', available: true },
];

export const collectors: Collector[] = [
  {
    id: 'col-1',
    name: 'James Mwangi',
    photo: '/collectors/james.jpg',
    phone: '+254 712 345 678',
    rating: 4.9,
  },
  {
    id: 'col-2',
    name: 'Grace Wanjiku',
    photo: '/collectors/grace.jpg',
    phone: '+254 723 456 789',
    rating: 4.8,
  },
  {
    id: 'col-3',
    name: 'Peter Omondi',
    photo: '/collectors/peter.jpg',
    phone: '+254 734 567 890',
    rating: 4.7,
  },
];

export const mockBooking: Booking = {
  id: 'BK-2024-001',
  userId: 'user-1',
  tests: [labTests[0], labTests[1], labTests[2]],
  status: 'collector_en_route',
  scheduledDate: '2024-02-15',
  scheduledTime: '09:00 AM',
  address: '123 Kenyatta Avenue, Nakuru',
  collector: {
    ...collectors[0],
    eta: '15 mins',
    location: { lat: -0.2833, lng: 36.0667 },
  },
  paymentMethod: 'mpesa',
  paymentStatus: 'completed',
  totalAmount: 2700,
  createdAt: '2024-02-14T10:00:00Z',
  updatedAt: '2024-02-15T08:45:00Z',
};

export const mockResults: TestResult[] = [
  {
    id: 'res-1',
    bookingId: 'BK-2024-001',
    testName: 'Complete Blood Count',
    result: 'Hemoglobin: 14.5 g/dL, WBC: 7,500/μL, Platelets: 250,000/μL',
    normalRange: 'Hb: 12-16, WBC: 4,500-11,000, Plt: 150,000-400,000',
    status: 'normal',
    date: '2024-02-16',
    labName: 'AfyaGo Central Lab',
    verifiedBy: 'Dr. Sarah Kimani',
  },
  {
    id: 'res-2',
    bookingId: 'BK-2024-001',
    testName: 'Cholesterol Check',
    result: 'Total Cholesterol: 220 mg/dL, LDL: 145 mg/dL, HDL: 42 mg/dL',
    normalRange: 'TC: <200, LDL: <100, HDL: >40',
    status: 'abnormal',
    date: '2024-02-16',
    labName: 'AfyaGo Central Lab',
    verifiedBy: 'Dr. Sarah Kimani',
  },
  {
    id: 'res-3',
    bookingId: 'BK-2024-001',
    testName: 'Blood Sugar Test',
    result: '95 mg/dL',
    normalRange: '70-100 mg/dL',
    status: 'normal',
    date: '2024-02-16',
    labName: 'AfyaGo Central Lab',
    verifiedBy: 'Dr. Sarah Kimani',
  },
];

export const categories = [
  'All',
  'Hematology',
  'Cardiovascular',
  'Diabetes',
  'Liver',
  'Kidney',
  'Thyroid',
  'Infectious Disease',
  'Vitamins',
  'General',
  'Genetic',
];
